### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by dascandy** [tomtom-international/cpp-dependencies#4]
The tool so far has not been tried or tested on Windows.

**Comment by torbjoernk** [comment]
How am I supposed to specify the location of the Boost headers and static libs on Windows with VS2015 when using the provided solution file?

I've tried it with Boost 1.61 freshly downloaded and compiled with v140 (VS 2015) (`.\bootstrap.bat`, `.\b2 --prefix=MYPATH`).

Then, in the solution file, I specified in the target properties under _C/C++_ -> _General_ -> _Additional Include Directories_ the path to `MYPATH/include/boost_1_61/` and for _Linker_ -> _General_ -> _Additional Library Directories_ `MYPATH/lib` as well as for _Linker_ -> _Input_ -> _Additional Dependencies_ `libboost_filesystem-vc140-mt-1_61.lib` and `libboost_system-vc140_mt-1_61.lib` (and the `-gd` for the Debug build).

Compiles fine (i.e. finds headers) but fails at linker step with bunch of _unresolved external symbol_ to boost::system and boost::filesystem.

**Comment by dascandy** [comment]
That should have worked. I've got it working with 1.58 on VS2015 and 1.62 on VS2013. That may be a library order problem.

**Comment by torbjoernk** [comment]
Found my error: I was building/trying the default-selected _Release_ and _Debug_, which are x64 (i.e. 64bit). My boost was compiled for x86 (i.e. 32bit). Works find now. :+1:
